# Generated by Django 3.2.4 on 2021-07-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('idLogin', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Login')),
                ('nombreLogin', models.CharField(max_length=50, verbose_name='Nombre del Login')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca Vehiculo')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo del Automovil')),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.login')),
            ],
        ),
    ]
