# Generated by Django 3.2.4 on 2021-07-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Login',
            new_name='Categoria',
        ),
    ]
