# Generated by Django 3.0.8 on 2021-07-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_categoria_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='mecanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=80)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
