# Generated by Django 3.0.8 on 2021-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mecanico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanico',
            name='id',
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
