# Generated by Django 3.2.3 on 2021-06-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
