# Generated by Django 3.2.3 on 2021-07-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_categoria_vehiculo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='mecanicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=250, verbose_name='Telefono')),
                ('email', models.CharField(max_length=250, verbose_name='Telefono')),
                ('especialidad', models.CharField(max_length=250, verbose_name='Especialidad')),
                ('tiempo_exp', models.CharField(max_length=250, verbose_name='TiempoExp')),
            ],
        ),
    ]
